# Generated by Django 4.1.7 on 2023-03-16 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_school_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='password',
            field=models.CharField(default='123456', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='password',
            field=models.CharField(default='123456', max_length=20),
        ),
    ]
