# Generated by Django 4.1.7 on 2023-03-17 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_faculty_password_student_password'),
        ('main', '0006_location_attendance'),
    ]

    operations = [
    ]
