# Generated by Django 4.1.7 on 2023-04-07 03:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_merge_20230317_0203'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='course_code',
            field=models.CharField(default=1, max_length=8),
            preserve_default=False,
        ),
        # migrations.CreateModel(
        #     name='Feedback',
        #     fields=[
        #         ('id', models.IntegerField(primary_key=True, serialize=False)),
        #         ('comment', models.CharField(max_length=150)),
        #         ('topic', models.CharField(max_length=10)),
        #         ('dept_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.department')),
        #         ('school_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.school')),
        #         ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.student')),
        #     ],
        # ),
    ]
