# Generated by Django 4.1.7 on 2023-04-20 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_enrollment_course_code_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='KU_events',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('heading', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=250)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('comment', models.CharField(max_length=150)),
                ('topic', models.CharField(max_length=10)),
                ('dept_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.department')),
                ('school_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.school')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.student')),
            ],
        ),
        migrations.CreateModel(
            name='Dept_events',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('heading', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=250)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('dept_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.department')),
            ],
        ),
    ]
